name: Build Release

on:
  push:
    branches:
      - master

jobs:
  release_mac:
    name: Release Mac App
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Yarn
        run: npm i -g yarn@latest

      - name: Install Dependencies and Build App
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CI: false
        run: yarn install && yarn build

      - name: Publish Dmg/Zip
        run:  yarn publish:mac

  release_linux:
    name: Release Linux App
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Yarn
        run: npm i -g yarn@latest

      - name: Install Snapcraft
        run: sudo apt install snapd snap snapcraft
        run: sudo snap install multipass
        run: sudo snap install review-tools

      - name: Install Dependencies and Build App
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CI: false
        run: yarn install && yarn build

      - name: Publish Deb/AppImage
        run:  yarn publish:linux
